### PR TITLE
Fix qsort

### PR DESCRIPTION
**Pull request by simonlindholm**
I messed up the implementation, forgetting that qsort actually needed to be able to access the memory of the pointers you pass it... This fixes an ld segfault.

### CODE REVIEW

**Comment by AngheloAlf** [comment]
Do you have any steps to recreate the segfault?

**Comment by simonlindholm** [comment]
It was something like compile
```
int glob2;
void foo2(void) {
	glob2 = 1;
}
```
with IDO and then link it, I don't remember if -KPIC vs -non_shared mattered. I think any large enough binary should fail: it will crash as long as the sort call makes at least one reordering.

**Review by AngheloAlf — APPROVED** [review]
Doesn't segfault anymore when following the steps to reproduce. LGTM

**Review by hensldm — APPROVED** [review]
Seems fine to me.

**Pull request merged**
