### PR TITLE
Add ARM macOS building

### PR DESCRIPTION
**Pull request by tehzz**
I tried to merge in my ARM macOS code from the main repo. I haven't tested any of these yet, so it should probably be tested on at least x64 linux and ARM+x64 macOS. I don't know what the current status of Cygwin is...

### CODE REVIEW

**Comment by EllipticEllipsis** [comment]
**ARM Mac:**
I had to mkdir `build/5.3/out` and `build/7.1/out` when using the makefile or it would give up almost immediately. build.py appears fine.

With `TARGET=universal`, it gives
```
error: unable to open output file 'build/5.3/arm64-apple-macos11/libc_impl.o': 'No such file or directory'
```
which again required making the directory (same with `build/5.3/x86_64-apple-macos10.14`)

Both universal and ARM-only OK for MM once building recomp completes successfully.

**Comment by EllipticEllipsis** [comment]
Works fine for WSL's linux too, OKs OoT. The makefile does not have issues with making the directories on WSL, for whatever reason.

**Comment by tehzz** [comment]
Whoops sorry you caught me on a trip

Did you use homebrew `gmake`/not system make? I could probably adapt the makefile to work with older make if that's necessary

**Comment by EllipticEllipsis** [comment]
Yeah, I think I just used `make`, since it's never made a difference before. If it's easy to do, I think it'd be worth it.

**Comment by tehzz** [comment]
Long time coming, but I had some time to support the macOS system make

**Pull request merged**
